from __future__ import annotations

import json
import os
import re
import sys
import textwrap
from pathlib import Path

from .models import ActionType, RpaProject
from .control_flow import CONTROL_TYPES, parse_control_flow


def generate_python(project: RpaProject, project_dir: Path) -> Path:
    out_dir = Path(project_dir) / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "generated_rpa.py"
    _write_generated_requirements(out_dir)
    main_python = _main_python_path()
    runner_python = _runner_python_reference(out_dir, main_python)
    runner_exe = _runner_exe_reference(out_dir, _main_exe_path())
    _write_generated_runner(out_dir, runner_python, runner_exe)
    function_lines: list[str] = []
    runtime_input_data = project.to_dict().get("runtime_inputs", {})
    for index, action in enumerate(project.actions, start=1):
        if action.action == ActionType.PYTHON_CODE.value:
            function_lines.extend(_python_code_function(index, action.data.get("name") or action.name or "python_code", str(action.data.get("code", ""))))

    lines: list[str] = [
        "# Generated by Python RPA Recorder.",
        "#",
        "# Run from this generated folder with PowerShell:",
        "#   cd generated",
        "#   .\\run_generated.ps1",
        "#",
        "# Manual equivalent:",
        f"#   {runner_exe} --run-generated generated_rpa.py",
        "",
        "import time",
        "import os",
        "import getpass",
        "from datetime import date",
        "from pathlib import Path",
        "import cv2",
        "import numpy as np",
        "from PIL import ImageGrab, Image",
        "import pyautogui",
        "",
        "PROJECT_DIR = Path(__file__).resolve().parent.parent",
        "SCREENSHOT_DIR = PROJECT_DIR / 'screenshots'",
        f"VARIABLES = {json.dumps(project.variables, indent=4)}",
        f"RUNTIME_INPUTS = {runtime_input_data!r}",
        "RUNTIME_VARIABLES = dict(VARIABLES)",
        f"PRE_CLICK_PAUSE = {_delay_literal(project.settings.pre_click_pause)}",
        "",
        f"pyautogui.FAILSAFE = {bool(project.settings.pyautogui_failsafe)!r}",
        "pyautogui.PAUSE = 0.15",
        "",
        "def resolve(value):",
        "    if not isinstance(value, str):",
        "        return value",
        "    for key, val in RUNTIME_VARIABLES.items():",
        "        value = value.replace('{{' + key + '}}', str(val))",
        "    missing = re.findall(r'\\{\\{([A-Za-z_][A-Za-z0-9_]*)\\}\\}', value)",
        "    if missing:",
        "        raise KeyError(f'Missing variable: {missing[0]}')",
        "    return value",
        "",
        "def as_int(value):",
        "    return int(float(resolve(value)))",
        "",
        "def as_float(value):",
        "    return float(resolve(value))",
        "",
        "def prompt_runtime_inputs():",
        "    values = {}",
        "    for name, definition in RUNTIME_INPUTS.items():",
        "        kind = definition.get('type', 'text')",
        "        default = definition.get('default', '')",
        "        required = bool(definition.get('required', True))",
        "        options = definition.get('options') or []",
        "        env_value = os.environ.get('RPA_INPUT_' + name)",
        "        if env_value is not None:",
        "            raw = env_value",
        "        elif kind == 'password' or definition.get('sensitive'):",
        "            raw = getpass.getpass(f'{name}: ') or default",
        "        elif kind == 'dropdown' and options:",
        "            print(f'{name} choices: ' + ', '.join(options))",
        "            raw = input(f'{name} [{default}]: ').strip() or default",
        "        else:",
        "            raw = input(f'{name} [{default}]: ').strip() or default",
        "        if required and (raw is None or str(raw).strip() == ''):",
        "            raise ValueError(f'{name}: a value is required')",
        "        if kind == 'number' and raw != '':",
        "            number = float(raw)",
        "            raw = int(number) if number.is_integer() else number",
        "        elif kind == 'date' and raw != '':",
        "            raw = date.fromisoformat(str(raw)).isoformat()",
        "        elif kind == 'dropdown' and options and raw not in options:",
        "            raise ValueError(f'{name}: choose one of {options}')",
        "        elif kind in ('file', 'folder') and raw != '':",
        "            selected = Path(raw).expanduser()",
        "            if not selected.exists() or (kind == 'file' and not selected.is_file()) or (kind == 'folder' and not selected.is_dir()):",
        "                raise ValueError(f'{name}: invalid {kind} path')",
        "            raw = str(selected)",
        "        values[name] = raw",
        "    return values",
        "",
        "def check_stop():",
        "    return False",
        "",
        "def clipboard_text():",
        "    try:",
        "        import tkinter",
        "        root = tkinter.Tk()",
        "        root.withdraw()",
        "        value = root.clipboard_get()",
        "        root.destroy()",
        "        return value",
        "    except Exception:",
        "        return ''",
        "",
        "def virtual_screen_origin():",
        "    if os.name != 'nt':",
        "        return 0, 0",
        "    try:",
        "        import ctypes",
        "        return int(ctypes.windll.user32.GetSystemMetrics(76)), int(ctypes.windll.user32.GetSystemMetrics(77))",
        "    except Exception:",
        "        return 0, 0",
        "",
        "def find_image(path, confidence=0.86, grayscale=False, search_region=None, priority='highest_confidence', match_index=1):",
        "    screen = ImageGrab.grab(all_screens=os.name == 'nt').convert('RGB')",
        "    origin_x, origin_y = virtual_screen_origin()",
        "    region_x, region_y = origin_x, origin_y",
        "    if search_region:",
        "        region_x, region_y = as_int(search_region.get('x', origin_x)), as_int(search_region.get('y', origin_y))",
        "        left, top = max(0, region_x - origin_x), max(0, region_y - origin_y)",
        "        right = min(screen.width, left + max(1, as_int(search_region.get('width', screen.width))))",
        "        bottom = min(screen.height, top + max(1, as_int(search_region.get('height', screen.height))))",
        "        screen = screen.crop((left, top, right, bottom))",
        "    haystack = np.array(screen)",
        "    needle = np.array(Image.open(path).convert('RGB'))",
        "    conversion = cv2.COLOR_RGB2GRAY if grayscale else cv2.COLOR_RGB2BGR",
        "    haystack, needle = cv2.cvtColor(haystack, conversion), cv2.cvtColor(needle, conversion)",
        "    if needle.shape[1] > haystack.shape[1] or needle.shape[0] > haystack.shape[0]:",
        "        return False, 0, 0, needle.shape[1], needle.shape[0], 0.0",
        "    result = np.nan_to_num(cv2.matchTemplate(haystack, needle, cv2.TM_CCOEFF_NORMED), nan=-1.0)",
        "    candidates = []",
        "    work = result.copy()",
        "    for _ in range(50):",
        "        _, score, _, location = cv2.minMaxLoc(work)",
        "        if score < confidence:",
        "            break",
        "        candidates.append((float(score), location[0] + region_x, location[1] + region_y))",
        "        left, top = max(0, location[0] - needle.shape[1] + 1), max(0, location[1] - needle.shape[0] + 1)",
        "        right, bottom = min(work.shape[1], location[0] + needle.shape[1]), min(work.shape[0], location[1] + needle.shape[0])",
        "        work[top:bottom, left:right] = -1.0",
        "    if not candidates:",
        "        _, score, _, location = cv2.minMaxLoc(result)",
        "        return False, location[0] + region_x, location[1] + region_y, needle.shape[1], needle.shape[0], float(score)",
        "    if priority == 'leftmost': chosen = min(candidates, key=lambda item: (item[1], -item[0]))",
        "    elif priority == 'rightmost': chosen = max(candidates, key=lambda item: (item[1], item[0]))",
        "    elif priority == 'topmost': chosen = min(candidates, key=lambda item: (item[2], -item[0]))",
        "    elif priority == 'bottommost': chosen = max(candidates, key=lambda item: (item[2], item[0]))",
        "    elif priority == 'match_index': chosen = sorted(candidates, reverse=True)[max(0, min(as_int(match_index) - 1, len(candidates) - 1))]",
        "    else: chosen = max(candidates)",
        "    return True, chosen[1], chosen[2], needle.shape[1], needle.shape[0], chosen[0]",
        "",
        "def wait_for_image(images, confidence=0.86, timeout=10, grayscale=False, search_region=None, priority='highest_confidence', match_index=1):",
        "    images = [images] if isinstance(images, (str, Path)) else list(images)",
        "    deadline = time.monotonic() + timeout",
        "    last, matched_image = (False, 0, 0, 0, 0, 0.0), ''",
        "    while time.monotonic() <= deadline:",
        "        for image in images:",
        "            current = find_image(PROJECT_DIR / resolve(image), confidence, grayscale, search_region, priority, match_index)",
        "            if current[5] > last[5]: last, matched_image = current, str(image)",
        "            if current[0]: return current, str(image)",
        "        time.sleep(0.1)",
        "    return last, matched_image",
        "",
        "def window_exists(title, case_sensitive=False):",
        "    wanted = str(title) if case_sensitive else str(title).casefold()",
        "    return any(wanted in (item if case_sensitive else item.casefold()) for item in pyautogui.getAllTitles())",
        "",
        "def path_exists(value, path_type='either'):",
        "    path = Path(resolve(value)).expanduser()",
        "    if not path.is_absolute():",
        "        path = PROJECT_DIR / path",
        "    return path.is_file() if path_type == 'file' else path.is_dir() if path_type == 'folder' else path.exists()",
        "",
        "def variable_condition(name, operator='equals', expected='', case_sensitive=False):",
        "    actual = RUNTIME_VARIABLES.get(name)",
        "    if operator == 'is_empty':",
        "        return actual is None or str(actual).strip() == ''",
        "    left, right = str(actual if actual is not None else ''), str(resolve(expected))",
        "    if not case_sensitive:",
        "        left, right = left.casefold(), right.casefold()",
        "    return right in left if operator == 'contains' else left == right",
        "",
        "def click_image(images, offset_x, offset_y, button='left', confidence=0.86, timeout=10, fallback=None, clicks=1, grayscale=False, search_region=None, priority='highest_confidence', match_index=1):",
        "    images, button = resolve(images), resolve(button)",
        "    offset_x, offset_y = as_int(offset_x), as_int(offset_y)",
        "    confidence, timeout = as_float(confidence), as_float(timeout)",
        "    fallback = tuple(as_int(value) for value in fallback) if fallback else None",
        "    (found, x, y, width, height, score), matched_image = wait_for_image(images, confidence, timeout, grayscale, search_region, priority, match_index)",
        "    if found:",
        "        print(f'Image matched: {matched_image}, confidence={score:.3f}')",
        "        time.sleep(PRE_CLICK_PAUSE)",
        "        click_x, click_y = x + offset_x, y + offset_y",
        "        pyautogui.click(click_x, click_y, button=button, clicks=clicks)",
        "        RUNTIME_VARIABLES['LAST_CLICK_X'], RUNTIME_VARIABLES['LAST_CLICK_Y'] = click_x, click_y",
        "        return",
        "    if fallback:",
        "        time.sleep(PRE_CLICK_PAUSE)",
        "        pyautogui.click(fallback[0], fallback[1], button=button, clicks=clicks)",
        "        RUNTIME_VARIABLES['LAST_CLICK_X'], RUNTIME_VARIABLES['LAST_CLICK_Y'] = fallback",
        "        return",
        "    raise RuntimeError(f'Images not found: {images}, best score={score:.3f}')",
        "",
        "def main():",
        "    global RUNTIME_VARIABLES, SELECTED_WINDOW_TARGET",
        "    RUNTIME_VARIABLES = dict(VARIABLES)",
        "    RUNTIME_VARIABLES.update({'RUN_DATE': date.today().isoformat(), 'CLIPBOARD_TEXT': clipboard_text(), 'LAST_CLICK_X': 0, 'LAST_CLICK_Y': 0})",
        "    RUNTIME_VARIABLES.update(prompt_runtime_inputs())",
        f"    time.sleep({_delay_literal(project.settings.start_delay)})",
    ]
    lines.insert(11, "import re")
    helper_insert = lines.index("def main():")
    lines[helper_insert:helper_insert] = _generated_window_helpers()
    if function_lines:
        insert_at = lines.index("def main():")
        lines[insert_at:insert_at] = function_lines
    flow = parse_control_flow(project.actions)
    if flow.issues:
        reasons = "; ".join(issue.reason for issue in flow.issues)
        raise ValueError(f"Cannot generate Python for an invalid control-flow structure: {reasons}")
    indent_level = 1
    for action_index, action in enumerate(project.actions):
        index = action_index + 1
        if action.action == ActionType.COMMENT.value:
            text = str(action.data.get("text", "")).strip().replace("\n", " | ")
            lines.append(f"{'    ' * indent_level}# Note: {text}")
            lines.append(f"{'    ' * indent_level}pass  # Comment step {index}")
            continue
        if action.action in CONTROL_TYPES:
            if not action.enabled:
                raise ValueError(f"Control step {index} cannot be disabled")
            prefix = "    " * indent_level
            data = action.data
            if action.action == ActionType.GROUP_START.value:
                lines.append(f"{prefix}# region {str(data.get('name') or 'Step group')}")
                lines.append(f"{prefix}pass  # Group marker step {index}")
            elif action.action == ActionType.GROUP_END.value:
                lines.append(f"{prefix}# endregion")
            elif action.action in (
                ActionType.IF_IMAGE_EXISTS.value,
                ActionType.IF_IMAGE_NOT_EXISTS.value,
                ActionType.IF_WINDOW_EXISTS.value,
                ActionType.IF_PATH_EXISTS.value,
                ActionType.IF_VARIABLE.value,
            ):
                expression = _condition_expression(action.action, data, project)
                variable = f"__condition_step_{index}"
                lines.append(f"{prefix}{variable} = {expression}")
                lines.append(f"{prefix}print('Step {index} condition:', {variable})")
                lines.append(f"{prefix}if {variable}:")
                indent_level += 1
            elif action.action == ActionType.ELSE.value:
                indent_level -= 1
                prefix = "    " * indent_level
                lines.append(f"{prefix}else:")
                indent_level += 1
            elif action.action == ActionType.END_IF.value:
                indent_level -= 1
                lines.append(f"{'    ' * indent_level}# End If (step {index})")
            elif action.action == ActionType.REPEAT_COUNT.value:
                loop_var = f"__loop_step_{index}"
                count_var = f"__loop_count_{index}"
                lines.append(f"{prefix}{count_var} = as_int({data.get('count', 1)!r})")
                lines.append(f"{prefix}for {loop_var} in range({count_var}):")
                indent_level += 1
                nested = "    " * indent_level
                lines.append(f"{nested}print(f'Step {index} loop: {{{loop_var} + 1}}/{{{count_var}}}')")
            elif action.action == ActionType.REPEAT_UNTIL.value:
                loop_var = f"__loop_step_{index}"
                max_var = f"__loop_max_{index}"
                lines.append(f"{prefix}{max_var} = as_int({data.get('max_iterations', 100)!r})")
                lines.append(f"{prefix}for {loop_var} in range({max_var}):")
                indent_level += 1
                lines.append(f"{'    ' * indent_level}print(f'Step {index} loop iteration: {{{loop_var} + 1}}')")
            elif action.action == ActionType.END_LOOP.value:
                start_index = flow.end_loop_start[action_index]
                start_action = project.actions[start_index]
                if start_action.action == ActionType.REPEAT_UNTIL.value:
                    start_step = start_index + 1
                    nested = "    " * indent_level
                    result_var = f"__until_step_{start_step}"
                    expression = _condition_expression(
                        str(start_action.data.get("condition_type", ActionType.IF_VARIABLE.value)),
                        start_action.data,
                        project,
                    )
                    lines.append(f"{nested}{result_var} = {expression}")
                    lines.append(f"{nested}print('Step {start_step} repeat-until condition:', {result_var})")
                    lines.append(f"{nested}if {result_var}:")
                    lines.append(f"{nested}    break")
                    lines.append(
                        f"{nested}if __loop_step_{start_step} + 1 >= __loop_max_{start_step}:"
                    )
                    lines.append(
                        f"{nested}    raise RuntimeError('Repeat Until step {start_step} reached its safety limit')"
                    )
                    lines.append(
                        f"{nested}time.sleep(as_float({start_action.data.get('iteration_delay', 0.1)!r}))"
                    )
                indent_level -= 1
                lines.append(f"{'    ' * indent_level}# End Loop (step {index})")
            elif action.action == ActionType.BREAK_LOOP.value:
                lines.append(f"{prefix}print('Step {index}: break loop')")
                lines.append(f"{prefix}break")
            continue
        if not action.enabled:
            lines.append(f"{'    ' * indent_level}# Action {index} disabled: {action.summary()}")
            continue
        emitted_at = len(lines)
        data = action.data
        delay = float(action.delay_before)
        is_click_image = action.action in (ActionType.CLICK_IMAGE.value, ActionType.DOUBLE_CLICK_IMAGE.value)
        # Click Image steps poll continuously with their own search timeout
        # (see click_image/wait_for_image above), so skip the fixed pre-wait
        # and click as soon as the target is found instead of always waiting
        # out the recorded delay.
        if delay and not is_click_image:
            lines.append(f"    time.sleep({_delay_literal(delay)})")
        lines.append(f"    # Action {index}: {action.summary()} [{action.action}]")
        if is_click_image:
            fallback = None
            if data.get("use_coordinate_fallback", True):
                fallback = [data.get("fallback_x", 0), data.get("fallback_y", 0)]
            clicks = 2 if action.action == ActionType.DOUBLE_CLICK_IMAGE.value else 1
            references = [str(data.get("image", ""))]
            references.extend(str(item) for item in data.get("reference_images", []) if str(item))
            lines.append(
                "    click_image("
                f"{references!r}, {data.get('click_offset_x', 0)!r}, {data.get('click_offset_y', 0)!r}, "
                f"button={data.get('button', 'left')!r}, confidence={data.get('confidence', project.settings.default_confidence)!r}, "
                f"timeout={data.get('timeout', project.settings.default_timeout)!r}, fallback={fallback!r}, clicks={clicks!r}, "
                f"grayscale={bool(data.get('grayscale', False))!r}, search_region={data.get('search_region')!r}, "
                f"priority={data.get('match_priority', 'highest_confidence')!r}, match_index={data.get('match_index', 1)!r})"
            )
        elif action.action == ActionType.TYPE_TEXT.value:
            if data.get("clear_first"):
                lines.append("    pyautogui.hotkey('ctrl', 'a')")
                lines.append("    pyautogui.press('backspace')")
            lines.append(f"    typed_value = resolve({data.get('text', '')!r})")
            lines.append(f"    pyautogui.write(typed_value, interval=as_float({data.get('interval', project.settings.typing_interval)!r}))")
            if str(data.get("output_variable", "")).strip():
                lines.append(f"    RUNTIME_VARIABLES[{str(data.get('output_variable')).strip()!r}] = typed_value")
        elif action.action == ActionType.PRESS_KEY.value:
            lines.append(f"    pyautogui.press(resolve({data.get('key', '')!r}), presses=as_int({data.get('count', 1)!r}), interval=as_float({data.get('interval', 0.0)!r}))")
        elif action.action == ActionType.HOTKEY.value:
            keys = ", ".join(
                f"resolve({str(key)!r})" if "{{" in str(key) else repr(str(key))
                for key in data.get("keys", [])
            )
            lines.append(f"    pyautogui.hotkey({keys})")
        elif action.action == ActionType.SCROLL.value:
            if data.get("move_to"):
                lines.append(f"    pyautogui.moveTo(as_int({data.get('x', 0)!r}), as_int({data.get('y', 0)!r}))")
            lines.append(f"    pyautogui.scroll(as_int({data.get('amount', 0)!r}))")
        elif action.action == ActionType.WAIT.value:
            lines.append(f"    time.sleep(as_float({data.get('seconds', delay)!r}))")
        elif action.action == ActionType.RUN_PYTHON.value:
            lines.append("    variables = RUNTIME_VARIABLES")
            for code_line in str(data.get("code", "")).splitlines() or [""]:
                lines.append(f"    {code_line}")
            if str(data.get("output_variable", "")).strip():
                lines.append(f"    RUNTIME_VARIABLES[{str(data.get('output_variable')).strip()!r}] = locals().get('result', '')")
        elif action.action == ActionType.PYTHON_CODE.value:
            function_name = _function_name(index, data.get("name") or action.name or "python_code")
            output_name = str(data.get("output_variable", "")).strip()
            if data.get("continue_on_error", False):
                lines.append("    try:")
                lines.append(f"        step_result = {function_name}(RUNTIME_VARIABLES, PROJECT_DIR, check_stop)")
                if output_name:
                    lines.append(f"        RUNTIME_VARIABLES[{output_name!r}] = step_result")
                lines.append("    except Exception as exc:")
                lines.append(f"        print('Step {index} Python Code ignored error:', exc)")
            else:
                lines.append(f"    step_result = {function_name}(RUNTIME_VARIABLES, PROJECT_DIR, check_stop)")
                if output_name:
                    lines.append(f"    RUNTIME_VARIABLES[{output_name!r}] = step_result")
        elif action.action == ActionType.OPEN_FILE.value:
            lines.append("    import subprocess")
            lines.append(f"    opened_path = resolve({data.get('path', '')!r})")
            lines.append("    subprocess.Popen([opened_path], shell=True)")
            lines.append(f"    time.sleep(as_float({data.get('wait_after', 1.0)!r}))")
            if str(data.get("output_variable", "")).strip():
                lines.append(f"    RUNTIME_VARIABLES[{str(data.get('output_variable')).strip()!r}] = opened_path")
        elif action.action == ActionType.CLICK_COORDINATE.value:
            lines.append("    time.sleep(PRE_CLICK_PAUSE)")
            lines.append(f"    click_x, click_y = as_int({data.get('x', 0)!r}), as_int({data.get('y', 0)!r})")
            lines.append(f"    pyautogui.click(click_x, click_y, button=resolve({data.get('button', 'left')!r}))")
            lines.append("    RUNTIME_VARIABLES['LAST_CLICK_X'], RUNTIME_VARIABLES['LAST_CLICK_Y'] = click_x, click_y")
        elif action.action == ActionType.MOUSE_MOVE.value:
            lines.append(f"    pyautogui.moveTo(as_int({data.get('x', 0)!r}), as_int({data.get('y', 0)!r}), duration=as_float({data.get('duration', 0.2)!r}))")
        elif action.action == ActionType.DRAG.value:
            lines.append(f"    pyautogui.moveTo(as_int({data.get('start_x', 0)!r}), as_int({data.get('start_y', 0)!r}), duration=as_float({data.get('move_duration', 0.2)!r}))")
            lines.append(f"    drag_x, drag_y = as_int({data.get('end_x', 0)!r}), as_int({data.get('end_y', 0)!r})")
            lines.append(f"    pyautogui.dragTo(drag_x, drag_y, duration=as_float({data.get('duration', 0.5)!r}), button=resolve({data.get('button', 'left')!r}))")
            lines.append("    RUNTIME_VARIABLES['LAST_CLICK_X'], RUNTIME_VARIABLES['LAST_CLICK_Y'] = drag_x, drag_y")
        elif action.action in {
            ActionType.SELECT_WINDOW.value, ActionType.WAIT_WINDOW.value,
            ActionType.ACTIVATE_WINDOW.value, ActionType.MAXIMIZE_WINDOW.value,
            ActionType.MINIMIZE_WINDOW.value, ActionType.RESTORE_WINDOW.value,
            ActionType.CLOSE_WINDOW.value, ActionType.CLICK_WINDOW_RELATIVE.value,
            ActionType.MOVE_WINDOW_RELATIVE.value,
        }:
            window = data.get("window") if isinstance(data.get("window"), dict) else {
                key: data[key] for key in (
                    "process_name", "window_title", "title_match", "class_name",
                    "timeout", "retry_interval", "multiple_match",
                ) if key in data
            }
            use_selected = bool(data.get("use_selected_window", False))
            target_var = f"__window_target_{index}"
            window_var = f"__window_{index}"
            lines.append(f"    {target_var} = prepare_window_target({window!r}, {use_selected!r})")
            relative_action = action.action in {
                ActionType.CLICK_WINDOW_RELATIVE.value, ActionType.MOVE_WINDOW_RELATIVE.value,
            }
            if not relative_action:
                lines.append(f"    {window_var} = resolve_window({target_var})")
            if action.action == ActionType.SELECT_WINDOW.value:
                lines.append(f"    SELECTED_WINDOW_TARGET = dict({target_var})")
                lines.append(f"    print('Step {index} selected window:', {window_var}['title'])")
            elif action.action == ActionType.WAIT_WINDOW.value:
                lines.append(f"    print('Step {index} found window:', {window_var}['title'])")
            elif action.action == ActionType.ACTIVATE_WINDOW.value:
                lines.append(f"    {window_var} = change_window({window_var}, 'activate')")
            elif action.action in {
                ActionType.MAXIMIZE_WINDOW.value, ActionType.MINIMIZE_WINDOW.value,
                ActionType.RESTORE_WINDOW.value,
            }:
                state = {
                    ActionType.MAXIMIZE_WINDOW.value: "maximize",
                    ActionType.MINIMIZE_WINDOW.value: "minimize",
                    ActionType.RESTORE_WINDOW.value: "restore",
                }[action.action]
                lines.append(f"    {window_var} = change_window({window_var}, {state!r})")
            elif action.action == ActionType.CLOSE_WINDOW.value:
                lines.append(f"    close_window({window_var})")
            else:
                operation = "click" if action.action == ActionType.CLICK_WINDOW_RELATIVE.value else "move"
                lines.append(
                    f"    relative_window_action({target_var}, {operation!r}, {data.get('relative_x', 0)!r}, "
                    f"{data.get('relative_y', 0)!r}, scale={bool(data.get('scale_with_window', False))!r}, "
                    f"original_width={data.get('original_window_width', 0)!r}, original_height={data.get('original_window_height', 0)!r}, "
                    f"button={data.get('button', 'left')!r}, duration={data.get('duration', 0.2)!r}, "
                    f"fallback={([data.get('fallback_x', 0), data.get('fallback_y', 0)] if data.get('use_absolute_fallback', False) else None)!r})"
                )
        if indent_level != 1:
            prefix = "    " * indent_level
            for line_index in range(emitted_at, len(lines)):
                if lines[line_index].startswith("    "):
                    lines[line_index] = prefix + lines[line_index][4:]
    lines.extend([
        "",
        "if __name__ == '__main__':",
        "    try:",
        "        main()",
        "    except pyautogui.FailSafeException as exc:",
        "        raise RuntimeError('PyAutoGUI safety stop: move the mouse away from the screen corners and run again.') from exc",
        "    try:",
        "        pyautogui.alert('Flow completed', 'Python RPA Recorder')",
        "    except Exception:",
        "        print('Flow completed')",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _condition_expression(action_type: str, data: dict, project: RpaProject) -> str:
    if action_type in (ActionType.IF_IMAGE_EXISTS.value, ActionType.IF_IMAGE_NOT_EXISTS.value):
        expression = (
            f"find_image(PROJECT_DIR / resolve({data.get('image', '')!r}), "
            f"as_float({data.get('confidence', project.settings.default_confidence)!r}))[0]"
        )
        return f"not ({expression})" if action_type == ActionType.IF_IMAGE_NOT_EXISTS.value else expression
    if action_type == ActionType.IF_WINDOW_EXISTS.value:
        return (
            f"window_exists(resolve({data.get('window_title', '')!r}), "
            f"{bool(data.get('case_sensitive', False))!r})"
        )
    if action_type == ActionType.IF_PATH_EXISTS.value:
        return f"path_exists({data.get('path', '')!r}, {data.get('path_type', 'either')!r})"
    if action_type == ActionType.IF_VARIABLE.value:
        return (
            f"variable_condition({data.get('variable', '')!r}, {data.get('operator', 'equals')!r}, "
            f"{data.get('value', '')!r}, {bool(data.get('case_sensitive', False))!r})"
        )
    raise ValueError(f"Unsupported generated condition: {action_type}")


def _generated_window_helpers() -> list[str]:
    source = r'''
SELECTED_WINDOW_TARGET = None

def prepare_window_target(spec, use_selected=False):
    global SELECTED_WINDOW_TARGET
    spec = dict(spec or {})
    has_criteria = any(str(spec.get(key, '')).strip() for key in ('process_name', 'window_title', 'class_name'))
    if use_selected and not has_criteria:
        if SELECTED_WINDOW_TARGET is None:
            raise RuntimeError('No window has been selected by an earlier Select / Target Window step')
        selected = dict(SELECTED_WINDOW_TARGET)
        for key in ('timeout', 'retry_interval', 'multiple_match'):
            if key in spec:
                selected[key] = spec[key]
        spec = selected
    return {
        'process_name': str(resolve(spec.get('process_name', ''))).strip(),
        'window_title': str(resolve(spec.get('window_title', ''))).strip(),
        'title_match': str(resolve(spec.get('title_match', 'contains'))).lower(),
        'class_name': str(resolve(spec.get('class_name', ''))).strip(),
        'timeout': as_float(spec.get('timeout', 10.0)),
        'retry_interval': as_float(spec.get('retry_interval', 0.25)),
        'multiple_match': str(resolve(spec.get('multiple_match', 'error'))).lower(),
    }

def enumerate_windows():
    if os.name != 'nt':
        raise RuntimeError('Window-aware automation is available on Windows only')
    import ctypes
    from ctypes import wintypes
    user32, kernel32 = ctypes.windll.user32, ctypes.windll.kernel32
    user32.GetForegroundWindow.restype = wintypes.HWND
    windows = []
    callback_type = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)

    def process_name(process_id):
        process = kernel32.OpenProcess(0x1000, False, process_id)
        if not process:
            return ''
        try:
            size = wintypes.DWORD(32768)
            buffer = ctypes.create_unicode_buffer(size.value)
            return Path(buffer.value).name if kernel32.QueryFullProcessImageNameW(process, 0, buffer, ctypes.byref(size)) else ''
        finally:
            kernel32.CloseHandle(process)

    @callback_type
    def callback(hwnd, _lparam):
        if not user32.IsWindowVisible(hwnd) or user32.GetWindowTextLengthW(hwnd) <= 0:
            return True
        length = user32.GetWindowTextLengthW(hwnd) + 1
        title = ctypes.create_unicode_buffer(length)
        class_name = ctypes.create_unicode_buffer(256)
        process_id = wintypes.DWORD()
        rect = wintypes.RECT()
        user32.GetWindowTextW(hwnd, title, length)
        user32.GetClassNameW(hwnd, class_name, len(class_name))
        user32.GetWindowThreadProcessId(hwnd, ctypes.byref(process_id))
        if user32.GetWindowRect(hwnd, ctypes.byref(rect)) and rect.right > rect.left and rect.bottom > rect.top:
            windows.append({
                'handle': int(hwnd), 'title': title.value, 'class_name': class_name.value,
                'process_name': process_name(process_id.value),
                'left': int(rect.left), 'top': int(rect.top),
                'width': int(rect.right - rect.left), 'height': int(rect.bottom - rect.top),
                'minimized': bool(user32.IsIconic(hwnd)), 'maximized': bool(user32.IsZoomed(hwnd)),
            })
        return True

    user32.EnumWindows(callback, 0)
    return windows

def matching_windows(target):
    pattern = None
    if target['title_match'] == 'regex' and target['window_title']:
        pattern = re.compile(target['window_title'], re.IGNORECASE)
    result = []
    wanted_process = target['process_name'].casefold()
    for window in enumerate_windows():
        process = window['process_name'].casefold()
        if wanted_process and Path(wanted_process).stem != Path(process).stem:
            continue
        if target['class_name'] and window['class_name'].casefold() != target['class_name'].casefold():
            continue
        title = target['window_title']
        if title and target['title_match'] == 'exact' and window['title'].casefold() != title.casefold():
            continue
        if title and target['title_match'] == 'contains' and title.casefold() not in window['title'].casefold():
            continue
        if pattern is not None and pattern.search(window['title']) is None:
            continue
        result.append(window)
    return result

def resolve_window(target):
    deadline = time.monotonic() + max(0.0, target['timeout'])
    while True:
        matches = matching_windows(target)
        if matches:
            if len(matches) == 1 or target['multiple_match'] == 'first':
                return matches[0]
            if target['multiple_match'] == 'active':
                import ctypes
                active = int(ctypes.windll.user32.GetForegroundWindow() or 0)
                selected = next((item for item in matches if item['handle'] == active), None)
                if selected:
                    return selected
                raise RuntimeError(f'{len(matches)} windows matched, but none is active')
            raise RuntimeError(f'{len(matches)} windows matched; refine the process, title, or class')
        if time.monotonic() >= deadline:
            break
        time.sleep(max(0.05, min(target['retry_interval'], deadline - time.monotonic())))
    raise RuntimeError(f"Window not found after {target['timeout']:.1f}s: {target['process_name']} {target['window_title']}")

def change_window(window, operation):
    import ctypes
    from ctypes import wintypes
    user32 = ctypes.windll.user32
    user32.GetForegroundWindow.restype = wintypes.HWND
    hwnd = window['handle']
    if operation == 'activate':
        if window.get('minimized'):
            user32.ShowWindow(hwnd, 9)
        user32.BringWindowToTop(hwnd)
        if not user32.SetForegroundWindow(hwnd) and int(user32.GetForegroundWindow() or 0) != hwnd:
            raise PermissionError('Windows blocked target activation; use the same permission level as the target application')
    else:
        user32.ShowWindow(hwnd, {'maximize': 3, 'minimize': 6, 'restore': 9}[operation])
    time.sleep(0.15)
    return next((item for item in enumerate_windows() if item['handle'] == hwnd), window)

def close_window(window):
    import ctypes
    if not ctypes.windll.user32.PostMessageW(window['handle'], 0x0010, 0, 0):
        raise PermissionError('Windows blocked the request to close the target window')

def relative_window_action(target, operation, relative_x, relative_y, scale=False,
                           original_width=0, original_height=0, button='left', duration=0.2,
                           fallback=None):
    try:
        window = change_window(resolve_window(target), 'activate')
        offset_x, offset_y = as_float(relative_x), as_float(relative_y)
        if scale:
            offset_x *= window['width'] / max(1.0, as_float(original_width))
            offset_y *= window['height'] / max(1.0, as_float(original_height))
        x, y = window['left'] + round(offset_x), window['top'] + round(offset_y)
        if not (window['left'] <= x < window['left'] + window['width'] and window['top'] <= y < window['top'] + window['height']):
            raise RuntimeError('The relative point is outside the current window bounds')
    except Exception:
        if fallback is None:
            raise
        x, y = as_int(fallback[0]), as_int(fallback[1])
    if operation == 'click':
        time.sleep(PRE_CLICK_PAUSE)
        pyautogui.click(x, y, button=resolve(button))
        RUNTIME_VARIABLES['LAST_CLICK_X'], RUNTIME_VARIABLES['LAST_CLICK_Y'] = x, y
    else:
        pyautogui.moveTo(x, y, duration=as_float(duration))
'''
    return textwrap.dedent(source).strip("\n").splitlines() + [""]


def _write_generated_requirements(out_dir: Path) -> None:
    requirements = [
        "pyautogui>=0.9.54,<1",
        "Pillow>=10.4,<12",
        "opencv-python>=4.10,<5",
        "numpy>=2,<3",
    ]
    (out_dir / "requirements.txt").write_text("\n".join(requirements) + "\n", encoding="utf-8")


def _write_generated_runner(out_dir: Path, python_reference: str, exe_reference: str) -> None:
    script = [
        "$ErrorActionPreference = \"Stop\"",
        "$Root = Split-Path -Parent $MyInvocation.MyCommand.Path",
        "Set-Location $Root",
        "",
        f"$RecorderExe = Resolve-Path \"$Root\\{exe_reference}\" -ErrorAction SilentlyContinue",
        "if ($RecorderExe) {",
        "    & $RecorderExe --run-generated generated_rpa.py",
        "    exit $LASTEXITCODE",
        "}",
        "",
        f"$Python = Resolve-Path \"$Root\\{python_reference}\" -ErrorAction SilentlyContinue",
        "if ($Python) {",
        "    & $Python generated_rpa.py",
        "    exit $LASTEXITCODE",
        "}",
        "",
        "throw \"Could not find PythonRPARecorder.exe or the source .venv Python. To run on a PC without Python installed, keep this flow under the packaged PythonRPARecorder folder and regenerate Python from the app.\"",
        "",
    ]
    (out_dir / "run_generated.ps1").write_text("\n".join(script), encoding="utf-8")


def _delay_literal(value: object) -> str:
    return f"{float(value or 0):.2f}"


def _app_root() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parents[1]


def _main_python_path() -> Path:
    return _app_root() / ".venv" / "Scripts" / "python.exe"


def _main_exe_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve()
    return _app_root() / "PythonRPARecorder.exe"


def _runner_python_reference(out_dir: Path, main_python: Path) -> str:
    try:
        return os.path.relpath(main_python, out_dir)
    except ValueError:
        return str(main_python)


def _runner_exe_reference(out_dir: Path, main_exe: Path) -> str:
    try:
        return os.path.relpath(main_exe, out_dir)
    except ValueError:
        return str(main_exe)


def _function_name(index: int, name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_]+", "_", str(name).strip()).strip("_").lower() or "python_code"
    if clean[0].isdigit():
        clean = f"step_{clean}"
    return f"step_{index}_{clean}"


def _python_code_function(index: int, name: str, code: str) -> list[str]:
    function_name = _function_name(index, name)
    body = code.rstrip() or "pass"
    indented = textwrap.indent(body, "    ")
    return [
        "",
        f"def {function_name}(variables, project_dir, check_stop):",
        "    check_stop()",
        *indented.splitlines(),
        "    check_stop()",
        "    return locals().get('result')",
        "",
    ]
