from __future__ import annotations

import json
import os
import re
import sys
import textwrap
from pathlib import Path

from .models import ActionType, RpaProject


def generate_python(project: RpaProject, project_dir: Path) -> Path:
    out_dir = Path(project_dir) / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "generated_rpa.py"
    _write_generated_requirements(out_dir)
    main_python = _main_python_path()
    runner_python = _runner_python_reference(out_dir, main_python)
    runner_exe = _runner_exe_reference(out_dir, _main_exe_path())
    _write_generated_runner(out_dir, runner_python, runner_exe)
    function_lines: list[str] = []
    for index, action in enumerate(project.actions, start=1):
        if action.action == ActionType.PYTHON_CODE.value:
            function_lines.extend(_python_code_function(index, action.data.get("name") or action.name or "python_code", str(action.data.get("code", ""))))

    lines: list[str] = [
        "# Generated by Python RPA Recorder.",
        "#",
        "# Run from this generated folder with PowerShell:",
        "#   cd generated",
        "#   .\\run_generated.ps1",
        "#",
        "# Manual equivalent:",
        f"#   {runner_exe} --run-generated generated_rpa.py",
        "",
        "import time",
        "import os",
        "from pathlib import Path",
        "import cv2",
        "import numpy as np",
        "from PIL import ImageGrab, Image",
        "import pyautogui",
        "",
        "PROJECT_DIR = Path(__file__).resolve().parent.parent",
        "SCREENSHOT_DIR = PROJECT_DIR / 'screenshots'",
        f"VARIABLES = {json.dumps(project.variables, indent=4)}",
        "RUNTIME_VARIABLES = dict(VARIABLES)",
        f"PRE_CLICK_PAUSE = {_delay_literal(project.settings.pre_click_pause)}",
        "",
        f"pyautogui.FAILSAFE = {bool(project.settings.pyautogui_failsafe)!r}",
        "pyautogui.PAUSE = 0.15",
        "",
        "def resolve(value):",
        "    if not isinstance(value, str):",
        "        return value",
        "    for key, val in RUNTIME_VARIABLES.items():",
        "        value = value.replace('{{' + key + '}}', str(val))",
        "    missing = re.findall(r'\\{\\{([A-Za-z_][A-Za-z0-9_]*)\\}\\}', value)",
        "    if missing:",
        "        raise KeyError(f'Missing variable: {missing[0]}')",
        "    return value",
        "",
        "def check_stop():",
        "    return False",
        "",
        "def virtual_screen_origin():",
        "    if os.name != 'nt':",
        "        return 0, 0",
        "    try:",
        "        import ctypes",
        "        return int(ctypes.windll.user32.GetSystemMetrics(76)), int(ctypes.windll.user32.GetSystemMetrics(77))",
        "    except Exception:",
        "        return 0, 0",
        "",
        "def find_image(path, confidence=0.86):",
        "    haystack = np.array(ImageGrab.grab(all_screens=os.name == 'nt').convert('RGB'))",
        "    needle = np.array(Image.open(path).convert('RGB'))",
        "    haystack = cv2.cvtColor(haystack, cv2.COLOR_RGB2BGR)",
        "    needle = cv2.cvtColor(needle, cv2.COLOR_RGB2BGR)",
        "    result = cv2.matchTemplate(haystack, needle, cv2.TM_CCOEFF_NORMED)",
        "    _, max_val, _, max_loc = cv2.minMaxLoc(result)",
        "    origin_x, origin_y = virtual_screen_origin()",
        "    return max_val >= confidence, max_loc[0] + origin_x, max_loc[1] + origin_y, needle.shape[1], needle.shape[0], float(max_val)",
        "",
        "def wait_for_image(image, confidence=0.86, timeout=10):",
        "    path = PROJECT_DIR / image",
        "    deadline = time.monotonic() + timeout",
        "    last = (False, 0, 0, 0, 0, 0.0)",
        "    while time.monotonic() <= deadline:",
        "        last = find_image(path, confidence)",
        "        if last[0]:",
        "            return last",
        "        time.sleep(0.1)",
        "    return last",
        "",
        "def click_image(image, offset_x, offset_y, button='left', confidence=0.86, timeout=10, fallback=None, clicks=1):",
        "    found, x, y, width, height, score = wait_for_image(image, confidence, timeout)",
        "    if found:",
        "        time.sleep(PRE_CLICK_PAUSE)",
        "        pyautogui.click(x + offset_x, y + offset_y, button=button, clicks=clicks)",
        "        return",
        "    if fallback:",
        "        time.sleep(PRE_CLICK_PAUSE)",
        "        pyautogui.click(fallback[0], fallback[1], button=button, clicks=clicks)",
        "        return",
        "    raise RuntimeError(f'Image not found: {image}, best score={score:.3f}')",
        "",
        "def main():",
        "    global RUNTIME_VARIABLES",
        "    RUNTIME_VARIABLES = dict(VARIABLES)",
        f"    time.sleep({_delay_literal(project.settings.start_delay)})",
    ]
    lines.insert(11, "import re")
    if function_lines:
        insert_at = lines.index("def main():")
        lines[insert_at:insert_at] = function_lines
    for index, action in enumerate(project.actions, start=1):
        if not action.enabled:
            lines.append(f"    # Action {index} disabled: {action.summary()}")
            continue
        data = action.data
        delay = float(action.delay_before)
        if delay:
            lines.append(f"    time.sleep({_delay_literal(delay)})")
        lines.append(f"    # Action {index}: {action.summary()} [{action.action}]")
        if action.action in (ActionType.CLICK_IMAGE.value, ActionType.DOUBLE_CLICK_IMAGE.value):
            fallback = None
            if data.get("use_coordinate_fallback", True):
                fallback = [int(data.get("fallback_x", 0)), int(data.get("fallback_y", 0))]
            clicks = 2 if action.action == ActionType.DOUBLE_CLICK_IMAGE.value else 1
            lines.append(
                "    click_image("
                f"{data.get('image')!r}, {int(data.get('click_offset_x', 0))!r}, {int(data.get('click_offset_y', 0))!r}, "
                f"button={data.get('button', 'left')!r}, confidence={float(data.get('confidence', project.settings.default_confidence))!r}, "
                f"timeout={float(data.get('timeout', project.settings.default_timeout))!r}, fallback={fallback!r}, clicks={clicks!r})"
            )
        elif action.action == ActionType.TYPE_TEXT.value:
            if data.get("clear_first"):
                lines.append("    pyautogui.hotkey('ctrl', 'a')")
                lines.append("    pyautogui.press('backspace')")
            lines.append(f"    pyautogui.write(resolve({data.get('text', '')!r}), interval={float(data.get('interval', project.settings.typing_interval))!r})")
        elif action.action == ActionType.PRESS_KEY.value:
            lines.append(f"    pyautogui.press({data.get('key', '')!r}, presses={int(data.get('count', 1))!r}, interval={float(data.get('interval', 0.0))!r})")
        elif action.action == ActionType.HOTKEY.value:
            keys = ", ".join(repr(str(key)) for key in data.get("keys", []))
            lines.append(f"    pyautogui.hotkey({keys})")
        elif action.action == ActionType.SCROLL.value:
            if data.get("move_to"):
                lines.append(f"    pyautogui.moveTo({int(data.get('x', 0))!r}, {int(data.get('y', 0))!r})")
            lines.append(f"    pyautogui.scroll({int(data.get('amount', 0))!r})")
        elif action.action == ActionType.WAIT.value:
            lines.append(f"    time.sleep({_delay_literal(data.get('seconds', delay))})")
        elif action.action == ActionType.RUN_PYTHON.value:
            lines.append("    variables = RUNTIME_VARIABLES")
            for code_line in str(data.get("code", "")).splitlines() or [""]:
                lines.append(f"    {code_line}")
        elif action.action == ActionType.PYTHON_CODE.value:
            function_name = _function_name(index, data.get("name") or action.name or "python_code")
            if data.get("continue_on_error", False):
                lines.append("    try:")
                lines.append(f"        {function_name}(RUNTIME_VARIABLES, PROJECT_DIR, check_stop)")
                lines.append("    except Exception as exc:")
                lines.append(f"        print('Step {index} Python Code ignored error:', exc)")
            else:
                lines.append(f"    {function_name}(RUNTIME_VARIABLES, PROJECT_DIR, check_stop)")
        elif action.action == ActionType.OPEN_FILE.value:
            lines.append("    import subprocess")
            lines.append(f"    subprocess.Popen([resolve({data.get('path', '')!r})], shell=True)")
            lines.append(f"    time.sleep({_delay_literal(data.get('wait_after', 1.0))})")
        elif action.action == ActionType.CLICK_COORDINATE.value:
            lines.append("    time.sleep(PRE_CLICK_PAUSE)")
            lines.append(f"    pyautogui.click({int(data.get('x', 0))!r}, {int(data.get('y', 0))!r}, button={data.get('button', 'left')!r})")
    lines.extend([
        "",
        "if __name__ == '__main__':",
        "    try:",
        "        main()",
        "    except pyautogui.FailSafeException as exc:",
        "        raise RuntimeError('PyAutoGUI safety stop: move the mouse away from the screen corners and run again.') from exc",
        "    try:",
        "        pyautogui.alert('Flow completed', 'Python RPA Recorder')",
        "    except Exception:",
        "        print('Flow completed')",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _write_generated_requirements(out_dir: Path) -> None:
    requirements = [
        "pyautogui>=0.9.54,<1",
        "Pillow>=10.4,<12",
        "opencv-python>=4.10,<5",
        "numpy>=2,<3",
    ]
    (out_dir / "requirements.txt").write_text("\n".join(requirements) + "\n", encoding="utf-8")


def _write_generated_runner(out_dir: Path, python_reference: str, exe_reference: str) -> None:
    script = [
        "$ErrorActionPreference = \"Stop\"",
        "$Root = Split-Path -Parent $MyInvocation.MyCommand.Path",
        "Set-Location $Root",
        "",
        f"$RecorderExe = Resolve-Path \"$Root\\{exe_reference}\" -ErrorAction SilentlyContinue",
        "if ($RecorderExe) {",
        "    & $RecorderExe --run-generated generated_rpa.py",
        "    exit $LASTEXITCODE",
        "}",
        "",
        f"$Python = Resolve-Path \"$Root\\{python_reference}\" -ErrorAction SilentlyContinue",
        "if ($Python) {",
        "    & $Python generated_rpa.py",
        "    exit $LASTEXITCODE",
        "}",
        "",
        "throw \"Could not find PythonRPARecorder.exe or the source .venv Python. To run on a PC without Python installed, keep this flow under the packaged PythonRPARecorder folder and regenerate Python from the app.\"",
        "",
    ]
    (out_dir / "run_generated.ps1").write_text("\n".join(script), encoding="utf-8")


def _delay_literal(value: object) -> str:
    return f"{float(value or 0):.2f}"


def _app_root() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve().parent
    return Path(__file__).resolve().parents[1]


def _main_python_path() -> Path:
    return _app_root() / ".venv" / "Scripts" / "python.exe"


def _main_exe_path() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).resolve()
    return _app_root() / "PythonRPARecorder.exe"


def _runner_python_reference(out_dir: Path, main_python: Path) -> str:
    try:
        return os.path.relpath(main_python, out_dir)
    except ValueError:
        return str(main_python)


def _runner_exe_reference(out_dir: Path, main_exe: Path) -> str:
    try:
        return os.path.relpath(main_exe, out_dir)
    except ValueError:
        return str(main_exe)


def _function_name(index: int, name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_]+", "_", str(name).strip()).strip("_").lower() or "python_code"
    if clean[0].isdigit():
        clean = f"step_{clean}"
    return f"step_{index}_{clean}"


def _python_code_function(index: int, name: str, code: str) -> list[str]:
    function_name = _function_name(index, name)
    body = code.rstrip() or "pass"
    indented = textwrap.indent(body, "    ")
    return [
        "",
        f"def {function_name}(variables, project_dir, check_stop):",
        "    check_stop()",
        *indented.splitlines(),
        "    check_stop()",
        "",
    ]
